//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schoolmngt.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SMSystemConsettings : DbContext
    {
        public SMSystemConsettings()
            : base("name=SMSystemConsettings")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<district> districts { get; set; }
        public virtual DbSet<news> news { get; set; }
        public virtual DbSet<sport_event> sport_event { get; set; }
        public virtual DbSet<attendance> attendances { get; set; }
        public virtual DbSet<follow> follows { get; set; }
        public virtual DbSet<payment> payments { get; set; }
        public virtual DbSet<subject> subjects { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<donator> donators { get; set; }
        public virtual DbSet<reqservice> reqservices { get; set; }
        public virtual DbSet<reqItem> reqItems { get; set; }
        public virtual DbSet<school> schools { get; set; }
        public virtual DbSet<Principle> Principles { get; set; }
        public virtual DbSet<student> students { get; set; }
        public virtual DbSet<teacher> teachers { get; set; }
    }
}
