//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schoolmngt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class news
    {
        public int n_id { get; set; }
        public System.DateTime n_date { get; set; }
        public int t_id { get; set; }
        public int st_id { get; set; }
        public string headiline { get; set; }
        public string discription { get; set; }
        public string isConfirm { get; set; }
        public string st_name { get; set; }
        public string img { get; set; }
    }
}
