//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schoolmngt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Principle
    {
        public int pid { get; set; }
        public string P_Nic { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string str_year { get; set; }
        public string gender { get; set; }
        public Nullable<int> school_Id { get; set; }
        public string school { get; set; }
        public string email { get; set; }
    }
}
