//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schoolmngt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reqservice
    {
        public int r_id { get; set; }
        public int st_id { get; set; }
        public string name { get; set; }
        public System.DateTime ser_date { get; set; }
        public string description { get; set; }
        public string isconfirm { get; set; }
    }
}
