//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schoolmngt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class school
    {
        public int school_id { get; set; }
        public string school_name { get; set; }
        public string school_tp { get; set; }
        public int zone_id { get; set; }
        public string pNic { get; set; }
        public string pName { get; set; }
    }
}
