//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schoolmngt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sport_event
    {
        public int sportId { get; set; }
        public string sp_name { get; set; }
        public string sp_event { get; set; }
        public string place { get; set; }
        public string recode { get; set; }
        public string ranks { get; set; }
        public string sp_description { get; set; }
    }
}
