//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schoolmngt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public int stid { get; set; }
        public string st_name { get; set; }
        public string st_address { get; set; }
        public string st_gender { get; set; }
        public System.DateTime st_bdy { get; set; }
        public string st_year { get; set; }
        public Nullable<int> t_id { get; set; }
        public string email { get; set; }
    }
}
